### ISSUE TITLE
Figure out if there's a way to import the README into `src/lib.rs`

### ISSUE THREAD

**Issue by mbestavros** [enarx/iocuddle#5]
Per @npmccallum: https://github.com/enarx/iocuddle/pull/4#discussion_r463150742

**Comment by haraldh** [comment]
```rust
#![cfg_attr(feature = "nightly", feature(external_doc), doc(include = "../README.md"))]
```

only works on nightly currently see issue https://github.com/rust-lang/rust/issues/44732

**Comment by haraldh** [comment]
@npmccallum the other way round works with https://crates.io/crates/cargo-readme which creates the `README.md` from the crate documentation.

**Comment by npmccallum** [comment]
@mbestavros Do you want to try to set up a lint workflow on this that runs `cargo readme` and ensures that no changes to the `README.md` would be made?

**Comment by mbestavros** [comment]
@npmccallum Sure!
